version: 2

models:
  - name: stg_011h_classification
  - name: stg_bom_config_param
  - name: stg_bom_material_hierarchy
  - name: stg_bom_partial_segment_layer
  - name: stg_component_classification
  - name: stg_component_layer
  - name: stg_component_type
  - name: stg_material_generic
  - name: stg_material_specific
  - name: stg_partial_segment      

