version: 2

sources:
  - name: proyect
    database: "{{ env_var('PROJECT_ID', 'mvp-011h') }}" 
    schema: RAW_Constructive_System_TEMP
  
        

    tables:
      - name: bom_material_hierarchy
        

